spring:
  cloud:
    stream:
      binders:
        defaultRabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                addresses: 127.0.0.1
                port: 5672
                username: guest
                password: guest
      bindings:
        output: #通道的名称
          destination: exchange1 #表示要使用的exchange名称的定义
          content-type: application/json
          binder: defaultRabbit
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql:///:3306/do_test_database?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false
  #jackson:
   # date-format: yyyy-MM-dd HH:mm:ss
    #time-zone: GMT+8
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl